name: Generate Media

on:
  schedule:
    - cron: '0 5 * * *'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 13.2.0
      - name: Generate Media
        env:
          MAIN_ACCESS_TOKEN: ${{ secrets.MAIN_ACCESS_TOKEN }}
          WEDDING_ACCESS_TOKEN: ${{ secrets.WEDDING_ACCESS_TOKEN }}
        run: |
          yarn
          yarn media
      - name: Set git config
        uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to built branch
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: 'master'
          commit_message: 'Generate Media'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
