name: Generate Media

on:
  schedule:
    - cron: '23 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 13.2.0
      - name: Generate Media
        run: |
          yarn
          yarn media
      - name: Push to built branch
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: 'master'
          commit_message: 'Generate Media'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
