name: Renew Tokens

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 13.2.0
      - name: Renew Tokens
        env:
          PERSONAL_GH_TOKEN: ${{ secrets.PERSONAL_GH_TOKEN }}
          MAIN_ACCESS_TOKEN: ${{ secrets.MAIN_ACCESS_TOKEN }}
          WEDDING_ACCESS_TOKEN: ${{ secrets.WEDDING_ACCESS_TOKEN }}
        run: |
          yarn
          yarn renew
